# fly.toml app configuration file generated for inventorylite on 2024-07-19T08:52:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inventorylite'
primary_region = 'dfw'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = 'true'
  APP_ENV = 'production'
  APP_NAME = 'inventoryLite'
  APP_URL = 'https://inventorylite.fly.dev'
  BASE_URL = 'https://inventorylite.fly.dev'
  BROADCAST_DRIVER = 'log'
  CACHE_DRIVER = 'file'
  DB_CONNECTION = 'mysql'
  DB_DATABASE = 'inventoryLite'
  DB_HOST = 'mariadb-132302-0.cloudclusters.net'
  DB_PORT = '10070'
  FILESYSTEM_DISK = 'local'
  LOG_CHANNEL = 'stderr'
  LOG_DEPRECATIONS_CHANNEL = 'null'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  QUEUE_CONNECTION = 'sync'
  SANCTUM_STATEFUL_DOMAINS = 'https://inventorylite.fly.dev'
  SESSION_DRIVER = 'file'
  SESSION_LIFETIME = '300'
  SESSION_SECURE_COOKIE = 'true'
  VITE_APP_BASE_URL = 'https://inventorylite.fly.dev'
  VITE_APP_SOFTWARE_VERSION = '1.0'
  MAIL_MAILER='smtp'
  MAIL_HOST='smtp.gmail.com'
  MAIL_PORT='587'
  MAIL_USERNAME='mailserservice@gmail.com'
  MAIL_PASSWORD='wvlv yavl beiu vwpl'
  MAIL_ENCRYPTION='null'
  MAIL_FROM_ADDRESS='mailserservice@gmail.com'
  MAIL_FROM_NAME='inventoryLite'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = ""
  worker = "php artisan queue:listen --tries=3"

[machines]
  [machines.worker]
  name = "worker-machine" 
  size = "shared-cpu-1x"  
  count = 1
  auto_stop = false   
  auto_start = true


[deploy]
  release_command = "sh -c 'php artisan migrate --force && php artisan config:cache && php artisan route:cache'"
